### ISSUE TITLE
Library is very big

### ISSUE THREAD

**Issue by PureSpider** [husarnet/husarnet-esp32-arduino#1]
I'm using an ESP32-S3 and even very basic sketches like the included webserver example are too big to be used on the chip:
`Sketch uses 1544316 bytes (117%) of program storage space. Maximum is 1310720 bytes.`

Is there anything that can be done to decrease the size of the library, or some settings I could change to make more space available for program storage?

**Comment by fwlodarczyk** [comment]
Hi @PureSpider 

You can change Flash Size and Partition Scheme under `Tools` section in Arduino IDE.

![obraz](https://github.com/user-attachments/assets/1b6f6aed-8fe9-45c3-8e39-908d38a3f4cb)

![obraz](https://github.com/user-attachments/assets/75476803-4dc0-42d4-a734-2d1323ea816d)

Regards, Filip

**Comment by PureSpider** [comment]
While I appreciate the workaround, does the library really need to take ~700kb of memory? That's basically as much as the rest of the sketch _combined_. Is there anything that can be done to reduce the size of the library?
